In [2]:
import numpy as np
import pandas as pd

In [3]:
credit_card_data = pd.read_csv('/Users/chizurumokereolujie/Documents/AI RELATED/MACHINE LEARNING CLASS/Datasets/credit_data.csv')

In [4]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [5]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [7]:
credit_card_data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

## 0 -> Legit Transactions
## 1 -> Fraudulent Transactions

In [9]:
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [13]:
legit.shape

(284315, 31)

In [12]:
fraud.shape

(492, 31)

### Under Sampling

### Building a sampling datasets containing similar distribution of fraudelent and legit transactions

In [47]:
legit_sample = legit.sample(n =492)
legit_sample

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
132806,80119.0,0.863538,-1.162663,0.677782,0.716502,-1.325024,0.120047,-0.599809,0.092433,-0.355413,...,-0.102009,-0.109491,-0.190746,0.055707,0.352951,-0.211975,0.051535,0.064286,210.00,0
72782,54855.0,1.061382,-0.094312,-0.018056,0.562165,-0.243403,-0.745364,0.331823,-0.117618,0.016207,...,-0.352509,-1.286700,0.147665,0.037684,0.075584,0.113492,-0.068354,0.021494,96.00,0
282494,170937.0,-0.014903,0.764093,0.290211,-0.558930,0.441512,-1.176677,0.962167,-0.191769,-0.010515,...,-0.253725,-0.590726,0.097109,0.033186,-0.492227,0.138295,0.241794,0.098864,7.28,0
180768,124692.0,-0.153506,0.829253,0.296235,-1.006507,0.834404,-1.282441,1.331375,-0.521654,0.187662,...,-0.202293,-0.240523,0.123744,0.052724,-1.242330,-0.125332,0.142147,0.083181,0.89,0
174150,121796.0,1.545179,-0.798082,-0.812422,1.407132,-0.014266,0.801069,-0.114942,0.176216,0.821887,...,-0.376598,-1.267958,0.231327,0.161034,-0.336214,-1.148434,0.015311,-0.002945,204.44,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139236,83073.0,1.165261,0.105003,0.873685,2.426510,0.062870,1.492620,-0.644798,0.424510,0.372784,...,-0.267779,-0.537305,-0.078073,-1.338630,0.421255,0.025885,0.054486,0.016226,5.32,0
34299,37602.0,-0.144998,0.657672,0.574369,1.370170,-0.373458,0.414107,-0.849006,-2.626062,-0.947300,...,-1.067325,0.691684,-0.253136,0.002651,0.735668,-0.130657,0.099525,0.264890,120.40,0
186365,127071.0,2.292282,-1.300244,-1.419160,-1.657803,-0.878826,-0.812314,-0.774457,-0.259350,-1.430096,...,-0.431788,-0.940425,0.374253,0.494443,-0.311290,-0.448974,-0.023394,-0.043337,41.50,0
194081,130435.0,2.021126,-0.297305,-0.326872,0.134848,-0.645962,-0.721989,-0.445252,-0.130930,1.234551,...,-0.198703,-0.373947,0.366843,-0.117601,-0.456644,-0.278647,0.014797,-0.036906,1.46,0
99974,67364.0,-1.349902,1.625789,0.301104,-0.136139,-0.246421,-0.144988,-0.224897,1.108243,-0.744036,...,-0.156560,-0.590475,0.064248,-0.368401,-0.132633,0.114551,0.126142,-0.002783,9.54,0

In [48]:
legit_sample.shape

(492, 31)

In [49]:
new_datasets = pd.concat([legit_sample, fraud], axis=0)

In [50]:
new_datasets

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
132806,80119.0,0.863538,-1.162663,0.677782,0.716502,-1.325024,0.120047,-0.599809,0.092433,-0.355413,...,-0.102009,-0.109491,-0.190746,0.055707,0.352951,-0.211975,0.051535,0.064286,210.00,0
72782,54855.0,1.061382,-0.094312,-0.018056,0.562165,-0.243403,-0.745364,0.331823,-0.117618,0.016207,...,-0.352509,-1.286700,0.147665,0.037684,0.075584,0.113492,-0.068354,0.021494,96.00,0
282494,170937.0,-0.014903,0.764093,0.290211,-0.558930,0.441512,-1.176677,0.962167,-0.191769,-0.010515,...,-0.253725,-0.590726,0.097109,0.033186,-0.492227,0.138295,0.241794,0.098864,7.28,0
180768,124692.0,-0.153506,0.829253,0.296235,-1.006507,0.834404,-1.282441,1.331375,-0.521654,0.187662,...,-0.202293,-0.240523,0.123744,0.052724,-1.242330,-0.125332,0.142147,0.083181,0.89,0
174150,121796.0,1.545179,-0.798082,-0.812422,1.407132,-0.014266,0.801069,-0.114942,0.176216,0.821887,...,-0.376598,-1.267958,0.231327,0.161034,-0.336214,-1.148434,0.015311,-0.002945,204.44,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [51]:
new_datasets.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
132806,80119.0,0.863538,-1.162663,0.677782,0.716502,-1.325024,0.120047,-0.599809,0.092433,-0.355413,...,-0.102009,-0.109491,-0.190746,0.055707,0.352951,-0.211975,0.051535,0.064286,210.00,0
72782,54855.0,1.061382,-0.094312,-0.018056,0.562165,-0.243403,-0.745364,0.331823,-0.117618,0.016207,...,-0.352509,-1.286700,0.147665,0.037684,0.075584,0.113492,-0.068354,0.021494,96.00,0
282494,170937.0,-0.014903,0.764093,0.290211,-0.558930,0.441512,-1.176677,0.962167,-0.191769,-0.010515,...,-0.253725,-0.590726,0.097109,0.033186,-0.492227,0.138295,0.241794,0.098864,7.28,0
180768,124692.0,-0.153506,0.829253,0.296235,-1.006507,0.834404,-1.282441,1.331375,-0.521654,0.187662,...,-0.202293,-0.240523,0.123744,0.052724,-1.242330,-0.125332,0.142147,0.083181,0.89,0
174150,121796.0,1.545179,-0.798082,-0.812422,1.407132,-0.014266,0.801069,-0.114942,0.176216,0.821887,...,-0.376598,-1.267958,0.231327,0.161034,-0.336214,-1.148434,0.015311,-0.002945,204.44,0

In [52]:
new_datasets['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64